services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:3000
    volumes: 
      - ./:/workspace
    command: sleep infinity
  data: 
    image: postgres
    volumes: 
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment: 
      POSTGRES_USER: test
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: eshop

volumes:
  postgres-data: